version: '3.8'

services:
  # バックエンドサービス
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: patrolmanagement-backend
    restart: always
    ports:
      - "${PORT:-5001}:${PORT:-5001}"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-5001}
      - DB_URI=${DB_URI:-mongodb://mongodb:27017/patrolmanagement}
      - JWT_SECRET=${JWT_SECRET:-dev_jwt_secret}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - app-network

  # フロントエンドサービス
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: patrolmanagement-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:${PORT:-5000}/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  # MongoDBサービス
  mongodb:
    image: mongo:5.0
    container_name: patrolmanagement-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

  # 開発用のMongoExpressサービス（管理画面）
  mongo-express:
    image: mongo-express
    container_name: patrolmanagement-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - app-network
    profiles:
      - dev

volumes:
  mongodb-data:

networks:
  app-network:
    driver: bridge